spring:
  datasource:
    url: jdbc:mysql://192.87.18.33:3305/test?useUnicode=true&useSSL=true&characterEncoding=utf-8&rewriteBatchedStatements=true
    username: root
    password: root123
    hikari:
      maximumPoolSize: 5
      minimumIdle: 5
      idleTimeout: 600000
      connectionTimeout: 30000
      maxLifetime: 1800000



mybatis:
  typeAliasesPackage: jiao.springdemo.mybatis.entity
  mapperLocations: classpath:mapper/*Mapper.xml
logging:
  level:
    jiao.springdemo.mybatis.dao: debug